name: ejpeg.biz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#402b84'
    - '#978bbd'
    - '#000000'
    - '#d2cedf'
  brandStrength: 1
  lightness: 0.9121932052075863
  saturation: 0.509581551188603
  rhythmicContrast: 0.5768917489331216
purpose: []
