name: ejpeg.biz
favicon: null
layout_spectrum: 0.38158574840053916
typography_spectrum: 0.6087482792790979
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5051595645491034
  lightness: 0.9121932052075863
  saturation: 0.509581551188603
  rhythmicContrast: 0.5768917489331216
purpose: []
